### PR TITLE
[WIP]  Oops - conflicting changes

### PR DESCRIPTION
**Pull request by rjleveque**
I just realized @mandli has pushed a bunch of changes that overlap with mine, e.g. adding to paper.bib.  We'll have to merge them by hand....

### CODE REVIEW

**Comment by mandli** [comment]
Blast, sorry about that!  Hopefully it won't be too annoying to merge.

**Comment by rjleveque** [comment]
I'll try to take a look tomorrow.

**Comment by rjleveque** [comment]
@mandli: I just did a merge of our changes.

I'm planning to push some more changes to other parts of the paper later today.  I'm working on an Introduction in particular.

**Comment by rjleveque** [comment]
I've started using cleveref for citing equations and sections,
  http://www.howtotex.com/packages/automatic-clever-references-with-cleveref/

**Pull request merged**
